on: [push]

name: ARM builds

jobs:
  linux_arm7:
    name: Linux ARM builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["aarch64-unknown-linux-gnu", "arm-unknown-linux-musleabi"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: ${{ matrix.target }} build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - run: ls -lah target/*
      - uses: actions/upload-artifact@v2
        with:
          name: http-gpio-${{ matrix.target }}
          path: target/release/http-gpio
