on: [push]

name: ARM builds

jobs:
  cross_compile_linux_binaries:
    name: Linux builds
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: ["aarch64-unknown-linux-gnu", "arm-unknown-linux-musleabi", "x86_64-unknown-linux-gnu"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: ${{ matrix.target }} build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - run: ls -lah target/*/*
      - uses: actions/upload-artifact@v2
        with:
          name: http-gpio-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/http-gpio
